// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCioAHM0P8GhAa00OWIRk1ppMKx9e1JLNM',
    appId: '1:1064723019722:web:818163958fd8cab0af4133',
    messagingSenderId: '1064723019722',
    projectId: 'talkietalkie-vp1413',
    authDomain: 'talkietalkie-vp1413.firebaseapp.com',
    storageBucket: 'talkietalkie-vp1413.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxumDmIVIFdKJNdSEnh3-oCRhn_jU6new',
    appId: '1:1064723019722:android:070f81aabc306560af4133',
    messagingSenderId: '1064723019722',
    projectId: 'talkietalkie-vp1413',
    storageBucket: 'talkietalkie-vp1413.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCNqdw5nI-XK3vSHwbbCVv142gTul30Hs',
    appId: '1:1064723019722:ios:ded8f66ef108eef7af4133',
    messagingSenderId: '1064723019722',
    projectId: 'talkietalkie-vp1413',
    storageBucket: 'talkietalkie-vp1413.firebasestorage.app',
    iosBundleId: 'com.vp1413.yappie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCNqdw5nI-XK3vSHwbbCVv142gTul30Hs',
    appId: '1:1064723019722:ios:60c25c646dd14f90af4133',
    messagingSenderId: '1064723019722',
    projectId: 'talkietalkie-vp1413',
    storageBucket: 'talkietalkie-vp1413.firebasestorage.app',
    iosBundleId: 'com.example.yappieyappie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCioAHM0P8GhAa00OWIRk1ppMKx9e1JLNM',
    appId: '1:1064723019722:web:d8405963dce169c1af4133',
    messagingSenderId: '1064723019722',
    projectId: 'talkietalkie-vp1413',
    authDomain: 'talkietalkie-vp1413.firebaseapp.com',
    storageBucket: 'talkietalkie-vp1413.firebasestorage.app',
  );

}